Chang/connect to spotify backend
ucladevx/replay-frontend pull request #21
Opened 2022-10-26 17:55 UTC by jchangz01

- Wrote helper functions on client-side to request for Spotify auth credentials, acquire auth tokens, and upload tokens to specified User in the backend
- These functions are triggered when a user clicks on "Continue with Spotify" on the PlatformConnect.js page

2022-10-26 20:54 UTC, jakegreenbergbell requested changes
Great job on this! I left a couple really small changes. Mostly just to add comments so we know what is incomplete in this code when we go back in to fix it for production.

If we have somewhere where we describe what should be in the .env file for the backend please also add the new redirect url there.

2022-10-26 20:54 UTC, jakegreenbergbell commented on App.js
>    );
This is a mistake right?

2022-10-26 20:54 UTC, jakegreenbergbell commented on helpers/auth.js
> +    const response = await fetch('http://localhost:9000/auth/spotify-credentials');
Nit: may want to add comment so we know this path will need to be changed.

2022-10-26 20:54 UTC, jakegreenbergbell commented on helpers/auth.js
> +    const { response_type, client_id, scope, redirect_uri, show_dialog } = await getSpotifyCredentials();
Nit: once we get the new developers working on coding and you just managing, we might want to make a style guide, since I usually use camel case for variables.

2022-10-26 20:54 UTC, jakegreenbergbell commented on helpers/auth.js
> +    const response = await fetch('http://localhost:9000/auth/upload-spotify-token-data', {
Same as above, to add a comment to change before we launch.

2022-10-26 20:54 UTC, jakegreenbergbell commented on package.json
> +  }
Can we change this to `"scheme": "replay"` easily so just it doesn't become confusing.

2022-10-27 05:13 UTC, jchangz01 commented on App.js
>    );
You will fix this when you merge

2022-10-27 05:14 UTC, jchangz01 commented on helpers/auth.js
> +    const { response_type, client_id, scope, redirect_uri, show_dialog } = await getSpotifyCredentials();
Agreed

2022-10-27 05:14 UTC, jchangz01 commented on package.json
> +  }
Not quite sure what that method actually does

2022-10-28 18:49 UTC, merged