Made profile page and song pop up not hard coded.
ucladevx/replay-frontend pull request #27
Opened 2022-12-01 01:45 UTC by izakbunda

2022-12-01 19:23 UTC, jchangz01 commented on App.js
> +      <Stack.Navigator initialRouteName="Home">
Can you please change the initialRouteName back to "Landing"

2022-12-01 19:24 UTC, jchangz01 commented on App.js
> +          options={{ headerShown: false }}
You can go ahead and remove the "Home" Stack.screen (Lines 32-36)

2022-12-01 19:25 UTC, jchangz01 commented on App.js
>          />
You can go ahead and remove the "Home" Stack.screen (Lines 32-36)

2022-12-01 19:29 UTC, jchangz01 requested changes
Make the changes in App.js and the rest should be fine

2023-01-14 00:22 UTC, izakbunda commented
Changes addressed.

2023-01-19 03:35 UTC, jchangz01 commented
Ok, it seems that Jake already created a component called Playlist.js. As a result, there is a merge conflict. To fix this, I think you should change your Playlist.js to ProfilePlaylist.js. And then utilize Jake's PlaylistImage.js component (you will need to rebase dev to see these changes) in your ProfilePlaylist.js line 16. Let me know if you have any questions.

2023-01-31 02:38 UTC, merged